/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.16
 * Generated at: 2023-12-05 05:50:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.memberone;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import memberone.*;

public final class modifyForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("memberone");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      memberone.StudentDAO dao = null;
      dao = (memberone.StudentDAO) _jspx_page_context.getAttribute("dao", jakarta.servlet.jsp.PageContext.PAGE_SCOPE);
      if (dao == null){
        dao = new memberone.StudentDAO();
        _jspx_page_context.setAttribute("dao", dao, jakarta.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>Update Form</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script language=\"javascript\" src=\"script.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");

String loginID = (String) session.getAttribute("loginID");
StudentVO vo = dao.getMember(loginID);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<form name=\"regForm\" method=\"post\" action=\"modifyProc.jsp\">\r\n");
      out.write("		<table border=\"1\">\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("\r\n");
      out.write("				<td colspan=\"2\" align=\"center\">회원 수정 정보 입력</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("\r\n");
      out.write("				<td align=\"right\">아이디 :</td>\r\n");
      out.write("\r\n");
      out.write("				<td>");
      out.print(vo.getId());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("\r\n");
      out.write("				<td align=\"right\">패스워드 :</td>\r\n");
      out.write("\r\n");
      out.write("				<td><input type=\"password\" name=\"pass\"\r\n");
      out.write("					value=\"");
      out.print(vo.getPass());
      out.write("\" /></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("\r\n");
      out.write("				<td align=\"right\">패스워드 확인:</td>\r\n");
      out.write("\r\n");
      out.write("				<td><input type=\"password\" name=\"repass\"\r\n");
      out.write("					value=\"");
      out.print(vo.getPass());
      out.write("\" /></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("\r\n");
      out.write("				<td align=\"right\">이름 :</td>\r\n");
      out.write("\r\n");
      out.write("				<td>");
      out.print(vo.getName());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"right\">전화번호 :</td>\r\n");
      out.write("\r\n");
      out.write("				<td><input type=\"text\" name=\"phone1\" size=\"4\"\r\n");
      out.write("					value=\"");
      out.print(vo.getPhone1());
      out.write("\" /> - <input type=\"text\" name=\"phone2\"\r\n");
      out.write("					size=\"5\" value=\"");
      out.print(vo.getPhone2());
      out.write("\" /> - <input type=\"text\"\r\n");
      out.write("					name=\"phone3\" size=\"5\" value=\"");
      out.print(vo.getPhone3());
      out.write("\" /></td>\r\n");
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("\r\n");
      out.write("				<td align=\"right\">이메일 :</td>\r\n");
      out.write("\r\n");
      out.write("				<td><input type=\"text\" name=\"email\" value=\"");
      out.print(vo.getEmail());
      out.write("\" /></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"right\">우편번호 :</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"zipcode\"\r\n");
      out.write("					value=\"");
      out.print(vo.getZipcode());
      out.write("\" /> <input type=\"button\" value=\"찾기\"\r\n");
      out.write("					onClick=\"zipCheck()\" /></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"right\">주소1 :</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"address1\" size=\"50\"\r\n");
      out.write("					value=\"");
      out.print(vo.getAddress1());
      out.write("\" /></td>\r\n");
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"right\">주소2 :</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"address2\" size=\"30\"\r\n");
      out.write("					value=\"");
      out.print(vo.getAddress2());
      out.write("\" /></td>\r\n");
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td colspan=\"2\" align=\"center\"><input type=\"button\"\r\n");
      out.write("					value=\"정보수정\" onClick=\"updateCheck()\" />&nbsp;&nbsp; <input\r\n");
      out.write("					type=\"button\" value=\"취소\"\r\n");
      out.write("					onClick=\"javascript:window.location='login.jsp'\" /></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
