/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.16
 * Generated at: 2023-12-04 06:23:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.memberone;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import memberone.*;

public final class zipCheck_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("memberone");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("      \r\n");
      memberone.StudentDAO dao = null;
      dao = (memberone.StudentDAO) _jspx_page_context.getAttribute("dao", jakarta.servlet.jsp.PageContext.PAGE_SCOPE);
      if (dao == null){
        dao = new memberone.StudentDAO();
        _jspx_page_context.setAttribute("dao", dao, jakarta.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("  \r\n");
 
 
 request.setCharacterEncoding("utf-8"); 
 
 String check = request.getParameter("check"); 
 
 String dong = request.getParameter("dong");  
 
 Vector<ZipCodeVO> zipcodeList = dao.zipcodeRead(dong);  
 int totalList = zipcodeList.size();  
 

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>우편번호검색</title><base>\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script language=\"JavaScript\" src=\"script.js\"></script>\r\n");
      out.write("<script> \r\n");
      out.write("function dongCheck(){\r\n");
      out.write("	if (document.zipForm.dong.value == \"\"){ \r\n");
      out.write("		alert(\"동이름을 입력하세요\"); \r\n");
      out.write("		 \r\n");
      out.write("		document.zipForm.dong.focus(); \r\n");
      out.write("		 \r\n");
      out.write("		return; \r\n");
      out.write("		 \r\n");
      out.write("		} \r\n");
      out.write("		 \r\n");
      out.write("		document.zipForm.submit(); \r\n");
      out.write("		 \r\n");
      out.write("		} \r\n");
      out.write("function sendAddress(zipcode,sido,gugun,dong,bunji){ \r\n");
      out.write("	var address =sido+\" \"+gugun+\" \"+dong+\" \"+bunji; \r\n");
      out.write("	 \r\n");
      out.write("	opener.document.regForm.zipcode.value=zipcode; \r\n");
      out.write("	 \r\n");
      out.write("	opener.document.regForm.address1.value=address; \r\n");
      out.write("	 \r\n");
      out.write("	self.close(); \r\n");
      out.write("	 \r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("		</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#FFFFCC\">\r\n");
      out.write("<b>우편번호 찾기</b>\r\n");
      out.write("<form name=\"zipForm\" method=\"post\" action=\"zipCheck.jsp\">\r\n");
      out.write("<table>\r\n");
      out.write("	<tr>\r\n");
      out.write("	<td>동이름 입력: <input name=\"dong\" type=\"text\"><input type=\"button\" value=\"검색\" onclick=\"dongCheck()\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<input type=\"hidden\" name=\"check\" value=\"n\">\r\n");
      out.write("</form>\r\n");
      out.write("<table> \r\n");
      out.write(" ");
 
if(check.equals("n")){ 

      out.write(' ');
      out.write('\r');
      out.write('\n');
 
 if (zipcodeList.isEmpty()) {  

      out.write("  \r\n");
      out.write(" \r\n");
      out.write(" <tr><td align=\"center\"><br/>검색된 결과가 없습니다.</td></tr> \r\n");
 } 
 
else { 
 

      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<tr><td align=\"center\"><br/> \r\n");
      out.write(" \r\n");
      out.write(" ※검색 후, 아래 우편번호를 클릭하면 자동으로 입력됩니다.</td></tr> \r\n");
 
 
for (int i=0;i<totalList;i++) { 
 
ZipCodeVO vo = zipcodeList.elementAt(i); 
 
String tempZipcode = vo.getZipcode(); 
 
String tempSido = vo.getSido(); 
 
String tempGugun = vo.getGugun(); 
 
String tempDong = vo.getDong(); 
 
String tempBunji = vo.getBunji(); 
 
if(tempBunji == null) tempBunji = " "; 
 

      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<tr><td> \r\n");
      out.write(" \r\n");
      out.write("<a href=\"javascript:sendAddress('");
      out.print(tempZipcode);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(tempSido);
      out.write("'  \r\n");
      out.write(",'");
      out.print(tempGugun);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(tempDong);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(tempBunji);
      out.write("')\">  ");
      out.print(tempZipcode);
      out.write("&nbsp;");
      out.print(tempSido);
      out.write("&nbsp;");
      out.print(tempGugun);
      out.write("\r\n");
      out.write("&nbsp;");
      out.print(tempDong);
      out.write("&nbsp;");
      out.print(tempBunji);
      out.write("</a><br>  \r\n");
 
}//end for 
 
}//end else 
 

      out.write(" \r\n");
      out.write(" \r\n");
}
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("</td></tr>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr><td align=\"center\"> \r\n");
      out.write(" \r\n");
      out.write("<a href=\"javascript:this.close();\">닫기</a> \r\n");
      out.write(" \r\n");
      out.write("</td></tr> \r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
